version: "3.4"

services:
  app:
    build: .
    volumes: 
      - .:/app
      - ./test:/opt/device
    command: ["go", "run", "main.go", "--device=/opt/device"]
    ports:
      - "5000:5000"
    devices:
      - "/sys/bus/w1/devices/28-0000071e1cf6:/sys/bus/w1/devices/28-0000071e1cf6"